#pragma config(Sensor, in1,    arm1,           sensorPotentiometer)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftColumn,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ColumnMiddle,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           cinchRelease,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightColumn,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          claw,          tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)


//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)


#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////


void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;


	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////


task autonomous()
{
motor[claw] = -63;
wait1Msec(10);
motor[backLeft] = 63;
motor[backRight] = 63;
motor[frontLeft] = 63;
motor[frontRight] = 63;
wait(3);
motor[backLeft] = 0;
motor[backRight] = 0;
motor[frontLeft] = 0;
motor[frontRight] = 0;
motor[leftColumn] = 63;
motor[rightColumn] = 63;
motor[ColumnMiddle] = 63;
wait(2);
motor[leftColumn] = 0;
motor[rightColumn] = 0;
motor[ColumnMiddle] = 0;
motor[backLeft] = 63;
motor[backRight] = -63;
motor[frontLeft] = 63;
motor[frontRight] = -63;
wait(4);
motor[backLeft] = -63;
motor[backRight] = 63;
motor[frontLeft] = -63;
motor[frontRight] = 63;

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
/*___________________________________________________


    Arm


 */

 void arm()
 {
   if(vexRT[Btn5D])
	{
		motor[leftColumn]=-63;
		motor[ColumnMiddle]=-63;
		motor[rightColumn]=-63;
		wait1Msec(10);
		motor[leftColumn]=0;
		motor[ColumnMiddle]=0;
		motor[rightColumn]=0;
}
	else if(vexRT[Btn5U])
	{
	while(SensorValue[arm1]<4010)
	{
		motor[leftColumn]=127;
		motor[ColumnMiddle]=127;
		motor[rightColumn]=127;
	}
		motor[leftColumn]=0;
		motor[ColumnMiddle]=0;
		motor[rightColumn]=0;
	}
 }

 //claw

 void clawArm()
 {
   if(vexRT[Btn7U])
   {
     motor[claw]=-63;
   }
   else if(vexRT[Btn7D])
   {
     motor[claw]=63;
   }
   else
   {
     motor[claw]=0;
   }
 }

 void cinch()
 {
   if(vexRT[Btn7L])
   {
     motor[cinchRelease]=63;
   }
   else if(vexRT[Btn7R])
   {
     motor[cinchRelease]=-63;
   }
   else
   {
     motor[cinchRelease]=0;
   }
 }

task usercontrol()
{
	int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;
	bool toggle=true;
	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.


	// Chassis movement
	//__________________________________________________
	  //Create "deadzone" for Y1/Ch3
		if(abs(vexRT[Ch4]) > threshold)
			Y1 = vexRT[Ch4];
		else
			Y1 = 0;
			//Create "deadzone" for X1/Ch4
		if(abs(vexRT[Ch1]) > threshold)
			X1 = vexRT[Ch1];
		else
			X1 = 0;
			//Create "deadzone" for X2/Ch1
		if(abs(vexRT[Ch2]) > threshold)
			X2 = vexRT[Ch2];
		else
			X2 = 0;

	if(vexRT[Btn8D])
	{
		toggle=!toggle;
	}
	if(toggle==false)
	{
	motor[frontRight] = (Y1 + X2 + X1);
	motor[backRight] =  (Y1 + X2 - X1);
	motor[frontLeft] = (Y1 - X2 - X1);
	motor[backLeft] =  (Y1 - X2 + X1);
	}
	//Remote Control Commands
	else
{
	motor[frontRight] = Y1 - X2 - X1;
	motor[backRight] =  Y1 - X2 + X1;
	motor[frontLeft] = Y1 + X2 + X1;
	motor[backLeft] =  Y1 + X2 - X1;
}

arm();
clawArm();
cinch();
	}




	  UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
}
