#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{

	//---------------------------------------------- Arcade driving
	motor[frontRight]=(vexRT[Ch1]-vexRT[Ch2])/2;
	motor[backRight]=(vexRT[Ch1]-vexRT[Ch2])/2;
	motor[frontLeft]=(vexRT[Ch1]+vexRT[Ch2])/2;
	motor[backLeft]=(vexRT[Ch1]+vexRT[Ch2])/2;
	//----------------------------------------------

	//---------------------------------------------- Claw



	//----------------------------------------------
	}
}
