#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Motor,  port2,           BackLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BackRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FrontLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FrontRight,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bLCDBacklight = true;									// Turn on LCD Backlight
	string mainBattery, backupBattery;
	int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;
	while(true)
	{
		//--------------------------------Battery
clearLCDLine(0);											// Clear line 1 (0) of the LCD
clearLCDLine(1);											// Clear line 2 (1) of the LCD

//Display the Primary Robot battery voltage
displayLCDString(0, 0, "Primary: ");
sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
displayNextLCDString(mainBattery);

//Display the Backup battery voltage
displayLCDString(1, 0, "Backup: ");
sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
displayNextLCDString(backupBattery);

//Short delay for the LCD refresh rate
wait1Msec(100);
		//-------------------------------Controls
		//Create "deadzone" for Y1/Ch3
if(abs(vexRT[Ch3]) > threshold)
Y1 = vexRT[Ch3];
else
Y1 = 0;
//Create "deadzone" for X1/Ch4
if(abs(vexRT[Ch4]) > threshold)
X1 = vexRT[Ch4];
else
X1 = 0;
//Create "deadzone" for X2/Ch1
if(abs(vexRT[Ch1]) > threshold)
X2 = vexRT[Ch1];
else
X2 = 0;
//Remote Control Commands
motor[FrontRight] = Y1 - X2 + X1;
motor[BackRight] =  Y1 - X2 - X1;
motor[FrontLeft] = Y1 + X2 - X1;
motor[BackLeft] =  Y1 + X2 + X1;
	}
}
